name: Free Disk Space

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h